FROM node:22-bookworm-slim

WORKDIR /app

COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

EXPOSE 3000

ENTRYPOINT ["docker-entrypoint.dev.sh"]
